name: Go-Build
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14
      - run: go mod download
      - name: Build
        run: go build -v .
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          args: release --snapshot --skip-publish --rm-dist
